spring.application.name=cruddemo
spring.datasource.url=jdbc:postgresql://localhost:5432/advanced_mappings
spring.datasource.username=springstudent
spring.datasource.password=springstudent

# turn off spring boot banner
spring.main.banner-mode=off

# reduce logging level
logging.level.root=warn