info.school.name=luv2code
info.app.name=My Super Cool Gradebook
info.app.description=a fun way to track student grades!
info.app.version=1.0.0

## Server Properties
server.port=1500

## Spring Datasource Properties
spring.datasource.url=jdbc:postgresql://localhost:5432/gradebook
spring.datasource.username=postgres
spring.datasource.password=
spring.sql.init.mode=always
spring.jpa.hibernate.ddl-auto=update
